import type { Translated } from './types.js';

/** Active substances (Polish INN, key without diacritics) → INN in the doctor's language + ATC. */
export const SUBSTANCES: Record<string, Translated & { atc: string }> = {
  // demo
  imatinib: { atc: 'L01EA01', en: 'imatinib', de: 'Imatinib', es: 'imatinib' },
  nilotynib: { atc: 'L01EA03', en: 'nilotinib', de: 'Nilotinib', es: 'nilotinib' },
  dazatynib: { atc: 'L01EA02', en: 'dasatinib', de: 'Dasatinib', es: 'dasatinib' },
  amlodypina: { atc: 'C08CA01', en: 'amlodipine', de: 'Amlodipin', es: 'amlodipino' },
  ibuprofen: { atc: 'M01AE01', en: 'ibuprofen', de: 'Ibuprofen', es: 'ibuprofeno' },
  rywaroksaban: { atc: 'B01AF01', en: 'rivaroxaban', de: 'Rivaroxaban', es: 'rivaroxabán' },
  // common
  paracetamol: { atc: 'N02BE01', en: 'paracetamol', de: 'Paracetamol', es: 'paracetamol' },
  'kwas acetylosalicylowy': {
    atc: 'B01AC06',
    en: 'acetylsalicylic acid',
    de: 'Acetylsalicylsäure',
    es: 'ácido acetilsalicílico',
  },
  metamizol: { atc: 'N02BB02', en: 'metamizole', de: 'Metamizol', es: 'metamizol' },
  ketoprofen: { atc: 'M01AE03', en: 'ketoprofen', de: 'Ketoprofen', es: 'ketoprofeno' },
  diklofenak: { atc: 'M01AB05', en: 'diclofenac', de: 'Diclofenac', es: 'diclofenaco' },
  metformina: { atc: 'A10BA02', en: 'metformin', de: 'Metformin', es: 'metformina' },
  atorwastatyna: { atc: 'C10AA05', en: 'atorvastatin', de: 'Atorvastatin', es: 'atorvastatina' },
  rosuwastatyna: { atc: 'C10AA07', en: 'rosuvastatin', de: 'Rosuvastatin', es: 'rosuvastatina' },
  simwastatyna: { atc: 'C10AA01', en: 'simvastatin', de: 'Simvastatin', es: 'simvastatina' },
  bisoprolol: { atc: 'C07AB07', en: 'bisoprolol', de: 'Bisoprolol', es: 'bisoprolol' },
  metoprolol: { atc: 'C07AB02', en: 'metoprolol', de: 'Metoprolol', es: 'metoprolol' },
  ramipryl: { atc: 'C09AA05', en: 'ramipril', de: 'Ramipril', es: 'ramipril' },
  peryndopryl: { atc: 'C09AA04', en: 'perindopril', de: 'Perindopril', es: 'perindopril' },
  losartan: { atc: 'C09CA01', en: 'losartan', de: 'Losartan', es: 'losartán' },
  walsartan: { atc: 'C09CA03', en: 'valsartan', de: 'Valsartan', es: 'valsartán' },
  hydrochlorotiazyd: {
    atc: 'C03AA03',
    en: 'hydrochlorothiazide',
    de: 'Hydrochlorothiazid',
    es: 'hidroclorotiazida',
  },
  furosemid: { atc: 'C03CA01', en: 'furosemide', de: 'Furosemid', es: 'furosemida' },
  warfaryna: { atc: 'B01AA03', en: 'warfarin', de: 'Warfarin', es: 'warfarina' },
  acenokumarol: { atc: 'B01AA07', en: 'acenocoumarol', de: 'Acenocoumarol', es: 'acenocumarol' },
  apiksaban: { atc: 'B01AF02', en: 'apixaban', de: 'Apixaban', es: 'apixabán' },
  dabigatran: { atc: 'B01AE07', en: 'dabigatran', de: 'Dabigatran', es: 'dabigatrán' },
  klopidogrel: { atc: 'B01AC04', en: 'clopidogrel', de: 'Clopidogrel', es: 'clopidogrel' },
  lewotyroksyna: { atc: 'H03AA01', en: 'levothyroxine', de: 'Levothyroxin', es: 'levotiroxina' },
  omeprazol: { atc: 'A02BC01', en: 'omeprazole', de: 'Omeprazol', es: 'omeprazol' },
  pantoprazol: { atc: 'A02BC02', en: 'pantoprazole', de: 'Pantoprazol', es: 'pantoprazol' },
  salbutamol: { atc: 'R03AC02', en: 'salbutamol', de: 'Salbutamol', es: 'salbutamol' },
  amoksycylina: { atc: 'J01CA04', en: 'amoxicillin', de: 'Amoxicillin', es: 'amoxicilina' },
  sertralina: { atc: 'N06AB06', en: 'sertraline', de: 'Sertralin', es: 'sertralina' },
  escitalopram: { atc: 'N06AB10', en: 'escitalopram', de: 'Escitalopram', es: 'escitalopram' },
  prednizon: { atc: 'H02AB07', en: 'prednisone', de: 'Prednison', es: 'prednisona' },
  allopurynol: { atc: 'M04AA01', en: 'allopurinol', de: 'Allopurinol', es: 'alopurinol' },
  tamsulosyna: { atc: 'G04CA02', en: 'tamsulosin', de: 'Tamsulosin', es: 'tamsulosina' },
  cetyryzyna: { atc: 'R06AE07', en: 'cetirizine', de: 'Cetirizin', es: 'cetirizina' },
  loratadyna: { atc: 'R06AX13', en: 'loratadine', de: 'Loratadin', es: 'loratadina' },
  insulina: { atc: 'A10A', en: 'insulin', de: 'Insulin', es: 'insulina' },
};
